[colors]
foreground = "#bbbac1"
background = "#1b1a20"
cursor_bg = "#bbbac1"
cursor_border = "#bbbac1"
cursor_fg = "#1b1a20"
selection_bg = "#413f4d"
selection_fg = "#bbbac1"
split = "#393842"
compose_cursor = "#e69875"
scrollbar_thumb = "#393842"

ansi = ["#121112", "#e67e80", "#a7c080", "#dbbc8a", "#8da0d6", "#817faf", "#53a8b8", "#bbbac1"]
brights = ["#393842", "#e67e80", "#a7c080", "#dbbc8a", "#8da0d6", "#d6a56f", "#53a8b8", "#bbbac1"]

[colors.tab_bar]
inactive_tab_edge = "#393842"
background = "#1b1a20"

[colors.tab_bar.active_tab]
fg_color = "#abbceb"
bg_color = "#413f4d"

[colors.tab_bar.inactive_tab]
fg_color = "#686675"
bg_color = "#1f1e26"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#686675"
bg_color = "#1f1e26"
# intensity = "Bold"

[colors.tab_bar.new_tab_hover]
fg_color = "#abbceb"
bg_color = "#413f4d"
intensity = "Bold"

[colors.tab_bar.new_tab]
fg_color = "#abbceb"
bg_color = "#1b1a20"

[metadata]
aliases = []
author = "Casey Miller"
name = "CAMPFIRE"