# CAMPFIRE Alacritty Colors
# Default colors
[colors.primary]
background = '#1b1a20'
foreground = '#bbbac1'

#[colors.cursor]
#cursor = '#bbbac1'
#text = '#1b1a20'

# Normal colors
[colors.normal]
black = '#121112'
red = '#e67e80'
green = '#a7c080'
yellow = '#dbbc8a'
blue = '#8da0d6'
magenta = '#817faf'
cyan = '#53a8b8'
white = '#bbbac1'

# Bright colors
[colors.bright]
black = '#393842'
red = '#e67e80'
green = '#a7c080'
yellow = '#dbbc8a'
blue = '#8da0d6'
magenta = '#d6a56f'
cyan = '#53a8b8'
white = '#bbbac1'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#e69875'

[[colors.indexed_colors]]
index = 17
color = '#abbceb'
