# name: DARKFOREST
# upstream: https://github.com/cdmill/neomodern.nvim/raw/main/extras/alacritty/darkforest.toml
# author: Casey Miller

# Default colors
[colors.primary]
background = '#181b1b'
# alternate, darker background = '#111312'
foreground = '#bbbac1'

#[colors.cursor]
#cursor = '#bbbac1'
#text = '#181b1b'

# Normal colors
[colors.normal]
black = '#111312'
red = '#e67e80'
green = '#7da77e'
yellow = '#dbbc7f'
blue = '#a7c080'
magenta = '#c3c082'
cyan = '#78b0a8'
white = '#bbbac1'

# Bright colors
[colors.bright]
black = '#7a8478'
red = '#e67e80'
green = '#7da77e'
yellow = '#dbbc7f'
blue = '#a7c080'
magenta = '#c76f82'
cyan = '#78b0a8'
white = '#bbbac1'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#e69875'

[[colors.indexed_colors]]
index = 17
color = '#d6a56f'
