# name: DAYLIGHT
# upstream: https://github.com/cdmill/neomodern.nvim/raw/main/extras/alacritty/daylight.toml
# author: Casey Miller

# Default colors
[colors.primary]
background = '#ffffff'
# alternate, darker background = '#000000'
foreground = '#111111'

#[colors.cursor]
#cursor = '#111111'
#text = '#ffffff'

# Normal colors
[colors.normal]
black = '#000000'
red = '#e6050a'
green = '#2ca32d'
yellow = '#f79b07'
blue = '#2e62f2'
magenta = '#4b46b8'
cyan = '#0293a3'
white = '#111111'

# Bright colors
[colors.bright]
black = '#9b9ba3'
red = '#e6050a'
green = '#2ca32d'
yellow = '#f79b07'
blue = '#2e62f2'
magenta = '#4b46b8'
cyan = '#0293a3'
white = '#111111'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#db7302'

[[colors.indexed_colors]]
index = 17
color = '#5d86f5'
