# ICECLIMBER Alacritty Colors
# Default colors
[colors.primary]
background = '#171718'
foreground = '#bbbac1'

#[colors.cursor]
#cursor = '#bbbac1'
#text = '#171718'

# Normal colors
[colors.normal]
black = '#2d2d2f'
red = '#e67e80'
green = '#7da77e'
yellow = '#dbbc8a'
blue = '#8da0d6'
magenta = '#817faf'
cyan = '#559ba3'
white = '#bbbac1'

# Bright colors
[colors.bright]
black = '#55555e'
red = '#e67e80'
green = '#7da77e'
yellow = '#dbbc8a'
blue = '#8da0d6'
magenta = '#e29eca'
cyan = '#559ba3'
white = '#bbbac1'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#d6a56f'

[[colors.indexed_colors]]
index = 17
color = '#abbceb'
