# name: ICECLIMBER colors for Alacritty
# url: https://github.com/alacritty/alacritty
# upstream: ${upstream}
# author: Casey Miller

# Default colors
[colors.primary]
background = '#171719'
# alternate, darker background = '#111113'
foreground = '#bbbac1'

#[colors.cursor]
#cursor = '#bbbac1'
#text = '#171719'

# Normal colors
[colors.normal]
black = '#111113'
red = '#e67e80'
green = '#629da3'
yellow = '#cc93b8'
blue = '#86a3f0'
magenta = '#8a88db'
cyan = '#6b6b99'
white = '#bbbac1'

# Bright colors
[colors.bright]
black = '#555568'
red = '#e67e80'
green = '#629da3'
yellow = '#cc93b8'
blue = '#86a3f0'
magenta = '#a8a6de'
cyan = '#6b6b99'
white = '#bbbac1'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#cfa18c'

[[colors.indexed_colors]]
index = 17
color = '#abbceb'
