# name: DAYLIGHT
# upstream: https://github.com/cdmill/neomodern.nvim/raw/main/extras/yazi/daylight.toml
# author: Casey Miller

[manager]
cwd = { fg = "#2e62f2" }

hovered         = { fg = "#0293a3", bg = "#f0f0f5" }
preview_hovered = { fg = "#0293a3", bg = "#f0f0f5" }

find_keyword  = { fg = "#5d86f5", italic = true }
find_position = { fg = "#5d86f5", bg = "reset", italic = true }

marker_copied   = { fg = "#2ca32d" }
marker_cut      = { fg = "${error}" }
marker_selected = { fg = "#5d86f5" }

tab_active   = { fg = "${builtin}", bg = "#d2d2dc" }
tab_inactive = { fg = "#9b9ba3", bg = "#d2d2dc" }
tab_width    = 1

count_cut      = { fg = "#5d86f5", bg = "#f0f0f5" }
count_copied   = { fg = "#5d86f5", bg = "#f0f0f5" }
count_selected = { fg = "#5d86f5", bg = "#f0f0f5" }

border_symbol = "│"
border_style  = { fg = "#9b9ba3" }

[mode]
normal_main   = { fg = "#ffffff", bg = "#2e62f2", bold = true }
normal_alt    = { fg = "#ffffff", bg = "#2e62f2", bold = true }
select_main   = { fg = "#ffffff", bg = "#4b46b8", bold = true }
select_alt    = { fg = "#ffffff", bg = "#4b46b8", bold = true }
unset_main    = { fg = "#ffffff", bg = "#0293a3", bold = true }
unset_alt     = { fg = "#ffffff", bg = "#0293a3", bold = true }

[status]
separator_open  = ""
separator_close = ""
separator_style = { fg = "#d2d2dc", bg = "#d2d2dc" }

progress_label  = { fg = "#5d86f5", bold = true }
progress_normal = { fg = "#5d86f5", bg = "#d2d2dc" }
progress_error  = { fg = "#ffffff", bg = "${error}" }

permissions_t = { fg = "#111111" }
permissions_r = { fg = "#f79b07" }
permissions_w = { fg = "#e6050a" }
permissions_x = { fg = "#2e62f2" }
permissions_s = { fg = "#111111" }

[input]
border   = { fg = "#9b9ba3" }
title    = {}
value    = {}
selected = { reversed = true }

[select]
border   = { fg = "#9b9ba3" }
active   = { fg = "#4b46b8" }
inactive = {}

[tasks]
border  = { fg = "#9b9ba3" }
title   = {}
hovered = { underline = true }

[which]
mask            = { bg = "#E6E6E6" }
cand            = { fg = "#0293a3" }
rest            = { fg = "#db7302" }
desc            = { fg = "#2ca32d" }
separator       = "  "
separator_style = { fg = "#111111"}

[help]
on      = { fg = "#db7302" }
run    = { fg = "#2ca32d" }
desc    = { fg = "#9b9ba3" }
hovered = { fg = "#0293a3", bg = "#f0f0f5", bold = true }
footer  = { fg = "#9b9ba3", bg = "#f0f0f5" }

[filetype]
rules = [
# Media
{ mime = "image/*", fg = "#4b46b8"},
{ mime = "{audio,video}/*", fg = "#2ca32d"},

# Archives
{ mime = "application/{,g}zip", fg = "#e6050a"},
{ mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#e6050a"},

# Fallback
{ name = "*", fg = "#111111"},
{ name = "*/", fg = "#2e62f2"}
]
  