# name: HOJICHA colors for Yazi
# url: https://github.com/sxyazi/yazi
# upstream: ${upstream}
# author: Casey Miller

[manager]
cwd = { fg = "#808796" }

hovered         = { fg = "#9c797d", bg = "#1b1c1d" }
preview_hovered = { fg = "#9c797d", bg = "#1b1c1d" }

find_keyword  = { fg = "#a7ab93", italic = true }
find_position = { fg = "#a7ab93", bg = "reset", italic = true }

marker_copied   = { fg = "#8a968f" }
marker_cut      = { fg = "${error}" }
marker_selected = { fg = "#a7ab93" }

tab_active   = { fg = "#a7ab93", bg = "#333333" }
tab_inactive = { fg = "#696969", bg = "#333333" }
tab_width    = 1

count_cut      = { fg = "#a7ab93", bg = "#1b1c1d" }
count_copied   = { fg = "#a7ab93", bg = "#1b1c1d" }
count_selected = { fg = "#a7ab93", bg = "#1b1c1d" }

border_symbol = "│"
border_style  = { fg = "#696969" }

[mode]
normal_main   = { fg = "#161616", bg = "#808796", bold = true }
normal_alt    = { fg = "#161616", bg = "#808796", bold = true }
select_main   = { fg = "#161616", bg = "#8a879c", bold = true }
select_alt    = { fg = "#161616", bg = "#8a879c", bold = true }
unset_main    = { fg = "#161616", bg = "#b0b58a", bold = true }
unset_alt     = { fg = "#161616", bg = "#b0b58a", bold = true }

[status]
separator_open  = ""
separator_close = ""
separator_style = { fg = "#333333", bg = "#333333" }

progress_label  = { fg = "#a7ab93", bold = true }
progress_normal = { fg = "#a7ab93", bg = "#333333" }
progress_error  = { fg = "#161616", bg = "${error}" }

permissions_t = { fg = "#adacac" }
permissions_r = { fg = "#b5ae84" }
permissions_w = { fg = "#9c797d" }
permissions_x = { fg = "#808796" }
permissions_s = { fg = "#856b6c" }

[input]
border   = { fg = "#696969" }
title    = {}
value    = {}
selected = { reversed = true }

[select]
border   = { fg = "#696969" }
active   = { fg = "#a18b7f" }
inactive = {}

[tasks]
border  = { fg = "#696969" }
title   = {}
hovered = { underline = true }

[which]
mask            = { bg = "#141414" }
cand            = { fg = "#9c797d" }
rest            = { fg = "#8a879c" }
desc            = { fg = "#8a968f" }
separator       = "  "
separator_style = { fg = "#856b6c"}

[help]
on      = { fg = "#8a879c" }
run    = { fg = "#8a968f" }
desc    = { fg = "#696969" }
hovered = { fg = "#9c797d", bg = "#1b1c1d", bold = true }
footer  = { fg = "#696969", bg = "#1b1c1d" }

[filetype]
rules = [
# Media
{ mime = "image/*", fg = "#a7ab93"},
{ mime = "{audio,video}/*", fg = "#8a968f"},

# Archives
{ mime = "application/{,g}zip", fg = "#9c797d"},
{ mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#9c797d"},

# Fallback
{ name = "*", fg = "#adacac"},
{ name = "*/", fg = "#808796"}
]
  