# NEOMODERN Alacritty Colors
# Default colors
[colors.primary]
background = '#1b1a20'
foreground = '#bbbac1'

#[colors.cursor]
#cursor = '#bbbac1'
#text = '#1b1a20'

# Normal colors
[colors.normal]
black = '#121112'
red = '#e67e80'
green = '#a7c080'
yellow = '#dbbc8a'
blue = '#8da0d6'
magenta = '#817faf'
cyan = '#53a8b8'
white = '#bbbac1'

# Bright colors
[colors.bright]
black = '#686675'
red = '#e67e80'
green = '#a7c080'
yellow = '#dbbc8a'
blue = '#8da0d6'
magenta = '#817faf'
cyan = '#53a8b8'
white = '#bbbac1'

