# NEOMODERN Alacritty Colors
# Default colors
[colors.primary]
background = '#181b1b'
foreground = '#bbbac1'

#[colors.cursor]
#cursor = '#bbbac1'
#text = '#181b1b'

# Normal colors
[colors.normal]
black = '#111312'
red = '#e67e80'
green = '#7da77e'
yellow = '#dbbc7f'
blue = '#a7c080'
magenta = '#d699b6'
cyan = '#78b0a8'
white = '#bbbac1'

# Bright colors
[colors.bright]
black = '#7a8478'
red = '#e67e80'
green = '#7da77e'
yellow = '#dbbc7f'
blue = '#a7c080'
magenta = '#d699b6'
cyan = '#78b0a8'
white = '#bbbac1'

