# NEOMODERN Alacritty Colors
# Default colors
[colors.primary]
background = '#ffffff'
foreground = '#111111'

#[colors.cursor]
#cursor = '#111111'
#text = '#ffffff'

# Normal colors
[colors.normal]
black = '#a7a7b0'
red = '#e6050a'
green = '#41a642'
yellow = '#fca921'
blue = '#5d86f5'
magenta = '#6b65d6'
cyan = '#0293a3'
white = '#111111'

# Bright colors
[colors.bright]
black = '#9b9ba3'
red = '#e6050a'
green = '#41a642'
yellow = '#fca921'
blue = '#5d86f5'
magenta = '#6b65d6'
cyan = '#0293a3'
white = '#111111'

